// Generated by https://quicktype.io

export interface DashBoardSummaryResponse {
  numberOfOrders: number;
  paidOrders: number;
  notPaidOrders: number;
  numberOfClients: number;
  numberOfProducts: number;
  productsWithNoInventoty: number;
  lowInventoty: number;
}
